AvaliacaoSawluz.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvaliacaoSawluz.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

       
    }
}

AvaliacaoSawluz.Web/Controllers/MenuController.cs
using AvaliacaoSawluz.Business;
using AvaliacaoSawluz.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvaliacaoSawluz.Web.Controllers
{
    public class MenuController : Controller
    {
        public ActionResult Index()
        {
            IMenuItemComponent bus = new MenuItemComponent();
            ViewBag.Name = string.Empty;
            return View(bus.ListMenuItems());
        }

        // GET: MenuItem/Create
        public ActionResult Create()
        {
            LoadRestaurantDropDown(null);
            return View();
        }

        // POST: MenuItem/Create
        [HttpPost]
        public ActionResult Create(MenuItem menuItem)
        {
            try
            {
                IMenuItemComponent bus = new MenuItemComponent();
                bus.SaveMenuItem(menuItem);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                LoadRestaurantDropDown(menuItem.RestaurantId);
                return View(menuItem);
            }
        }

        // GET: MenuItem/Edit/5
        public ActionResult Edit(long id)
        {
            IMenuItemComponent bus = new MenuItemComponent();
            MenuItem data = bus.GetMenuItem(id);
            LoadRestaurantDropDown(data.RestaurantId);
            return View(data);
        }

        // POST: MenuItem/Edit/5
        [HttpPost]
        public ActionResult Edit(MenuItem menuItem)
        {
            try
            {
                IMenuItemComponent bus = new MenuItemComponent();
                bus.SaveMenuItem(menuItem);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                LoadRestaurantDropDown(menuItem.RestaurantId);
                return View(menuItem);
            }
        }

        public JsonResult Delete(long id)
        {
            try
            {
                IMenuItemComponent bus = new MenuItemComponent();
                bus.RemoveMenuItem(id);
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
        }

        private void LoadRestaurantDropDown(long? value)
        {
            List<SelectListItem> dropDownData = new List<SelectListItem>();
            dropDownData.Add(new SelectListItem { Text = "Selecione", Value = "0", Selected = !value.HasValue });
            IRestaurantComponent bus = new RestaurantComponent();
            IEnumerable<Restaurant> restaurants = bus.ListRestaurants();
            dropDownData.AddRange(restaurants.OrderBy(o => o.Name).Select(item => new SelectListItem { Text = item.Name, Value = item.Id.ToString(), Selected = value.HasValue && item.Id == value.Value }));
            ViewBag.Restaurants = dropDownData;
        }
    }
}

AvaliacaoSawluz.Web/Controllers/RestaurantController.cs
using AvaliacaoSawluz.Business;
using AvaliacaoSawluz.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AvaliacaoSawluz.Web.Controllers
{
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Index()
        {
            IRestaurantComponent bus = new RestaurantComponent();
            ViewBag.Name = string.Empty;
            return View(bus.ListRestaurants());
        }

        [HttpPost]
        public ActionResult Search(string name)
        {
            IRestaurantComponent bus = new RestaurantComponent();
            ViewBag.Name = name;
            IEnumerable<Restaurant> restaurants = bus.ListRestaurants().Where(f => f.Name.Contains(name));
            return View("Index", restaurants);
        }
        // GET: Restaurant/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Restaurant/Create
        [HttpPost]
        public ActionResult Create(Restaurant restaurant)
        {
            try
            {
                IRestaurantComponent bus = new RestaurantComponent();
                bus.SaveRestaurant(restaurant);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(restaurant);
            }
        }

        // GET: Restaurant/Edit/5
        public ActionResult Edit(long id)
        {
            IRestaurantComponent bus = new RestaurantComponent();
            Restaurant data = bus.GetRestaurant(id);
            return View(data);
        }

        // POST: Restaurant/Edit/5
        [HttpPost]
        public ActionResult Edit( Restaurant restaurant)
        {
            try
            {
                IRestaurantComponent bus = new RestaurantComponent();
                bus.SaveRestaurant(restaurant);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(restaurant);
            }
        }

        public JsonResult Delete(long id)
        {
            try
            {
                IRestaurantComponent bus = new RestaurantComponent();
                bus.RemoveRestaurant(id);
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            catch
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

AvaliacaoSawluz.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicial";
}



<div class="row vertical-center">
    <div class="col-md-12 text-center">
        <img src="~/Content/Images/18292985-kebab--grilled-meat-bread-and-vegetables.jpg" style="width:250px;height:150px;" />
        <br />
        <br />
        <p><label>SISTEMA DE CADASTRO DE RESTAURANTES</label></p>
    </div>
</div>

AvaliacaoSawluz.Web/Views/Menu/Create.cshtml
@model AvaliacaoSawluz.Data.Models.MenuItem

@{
    ViewBag.Title = "Cadastro de Prato";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>CADASTRO DE PRATO</h3>


@using (Html.BeginForm("Create", "Menu", FormMethod.Post, new { id = "createForm" }))
{
    @Html.AntiForgeryToken()
    if (ViewData.ModelState[""] != null && ViewData.ModelState[""].Errors.Count > 0)
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            @Html.ValidationSummary(false)
        </div>
    }
    <div class="well">
        <fieldset class="col-md-12" >
            <legend>Dados</legend>
            <div class="col-md-12" style="z-index:5;">
                <label class="control-label col-md-12">Restaurante :</label>
                <div class="col-md-5">
                    @Html.DropDownList("RestaurantId", (List<SelectListItem>)ViewBag.Restaurants, new {  @class = "col-md-12 dropdown" })
                </div>
            </div>
            <div class="col-md-12" style="z-index:4;">
                <label class="control-label col-md-12">Nome :</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "col-md-12" } })
                </div>
            </div>
            <div class="col-md-12" style="z-index:3;">
                <label class="control-label col-md-12">Preço :</label>
                <div class="col-md-2">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "col-md-12 numeric" } })
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <a href="@Url.Action("Index","Menu")" class="btn btn-sm btn-danger col-md-2" style="margin-right:2vw;"><i class="fa fa-undo"></i>&nbsp;Cancelar</a>
                <button type="submit" id="save" class="btn btn-sm btn-success col-md-2"><i class="fa fa-floppy-o"></i>&nbsp;Salvar</button>
            </div>
        </fieldset>
    </div>
}

@section scripts{
    <script>
        $("#Price").on("keyup", function () {
            $(this).val(FormatField($(this).val()));
        });

        $('#createForm').on('submit', function (e) {
            if ($('#Name').val() == '') {
                alert("Nome é um campo obrigatório");
                e.preventDefault();
            }
        })


    </script>
}

AvaliacaoSawluz.Web/Views/Menu/Edit.cshtml
@model AvaliacaoSawluz.Data.Models.MenuItem

@{
    ViewBag.Title = "Cadastro de Prato";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>CADASTRO DE PRATO</h3>


@using (Html.BeginForm("Edit", "Menu", FormMethod.Post, new { id = "createForm" }))
{
    @Html.HiddenFor(model=> model.Id)
    @Html.AntiForgeryToken()
    if (ViewData.ModelState[""] != null && ViewData.ModelState[""].Errors.Count > 0)
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            @Html.ValidationSummary(false)
        </div>
    }
    <div class="well">
        <fieldset class="col-md-12">
            <legend>Dados</legend>
            <div class="col-md-12" style="z-index:5;">
                <label class="control-label col-md-12">Restaurante :</label>
                <div class="col-md-5">
                    @Html.DropDownList("RestaurantId", (List<SelectListItem>)ViewBag.Restaurants, new { @class = "col-md-12 dropdown" })
                </div>
            </div>
            <div class="col-md-12" style="z-index:4;">
                <label class="control-label col-md-12">Nome :</label>
                <div class="col-md-5">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "col-md-12" } })
                </div>
            </div>
            <div class="col-md-12" style="z-index:3;">
                <label class="control-label col-md-12">Preço :</label>
                <div class="col-md-2">
                    @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "col-md-12 numeric" } })
                </div>
            </div>
            <br />
            <br />
            <div class="row">
                <a href="@Url.Action("Index","Menu")" class="btn btn-sm btn-danger col-md-2" style="margin-right:2vw;"><i class="fa fa-undo"></i>&nbsp;Cancelar</a>
                <button type="submit" id="save" class="btn btn-sm btn-success col-md-2"><i class="fa fa-floppy-o"></i>&nbsp;Salvar</button>
            </div>
        </fieldset>
    </div>
}

@section scripts{
    <script>
        $("#Price").on("keyup", function () {
            $(this).val(FormatField($(this).val()));
        });

        $('#createForm').on('submit', function (e) {
            if ($('#Name').val() == '') {
                alert("Nome é um campo obrigatório");
                e.preventDefault();
            }
        })


    </script>
}

AvaliacaoSawluz.Web/Views/Menu/Index.cshtml
@model IEnumerable<AvaliacaoSawluz.Data.Models.MenuItem>

@{
    ViewBag.Title = "Pratos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>

</style>
<h3>PRATOS</h3>
<div class="row">
    <a href="@Url.Action("Create","Menu")" class="btn btn-sm btn-success col-md-2" style="margin-left:2vw;"><i class="fa fa-plus"></i>&nbsp;Cadastrar novo Prato</a>
</div>
<br /><br />
<table id="restaurants" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th class="col-md-1">&nbsp;</th>
            <th class="col-md-1">&nbsp;</th>
            <th class="col-md-6">
                @Html.DisplayNameFor(model => model.Restaurant.Name)
            </th>
            <th class="col-md-6">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="col-md-6">
                @Html.DisplayNameFor(model => model.Price)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">
                    <i class="fa fa-minus remove-item" title="Excluir" data-url="@Url.Action("Delete","Menu",new { id= item.Id })" style="color:red;"></i>
                </td>
                <td class="text-center">
                    <i class="fa fa-pencil edit-item" title="Editar" data-url="@Url.Action("Edit","Menu",new { id= item.Id })" style="color:cornflowerblue;"></i>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Restaurant.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td class="row text-right">
                        @(string.Format("{0:N}", item.Price))
                </td>
            </tr>
        }
    </tbody>

</table>
@section scripts{
    <script>
        $(document).ready(function () {
            $('#restaurants').DataTable({
                paging: false,
                autoWidth: true,
                info: false,
                lengthChange: false,
                ordering: false,
                searching: false,
                pageLength: 15
            });

            $('.edit-item').on('click', function () {
                var url = $(this).data('url');
                location.href = url;
            });
            $('.remove-item').on('click', function () {
                var url = $(this).data('url');
                $.getJSON(url, function (result) {
                    if (result == "Success") {
                        location.reload(true);
                    } else {
                        alert("Ocorreu um erro ao remover o item selecionado");
                    }
                });
            });
        })
    </script>
}

AvaliacaoSawluz.Web/Views/Restaurant/Create.cshtml
@model AvaliacaoSawluz.Data.Models.Restaurant

@{
    ViewBag.Title = "Cadastro de Restaurante";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>CADASTRO DE RESTAURANTE</h3>


@using (Html.BeginForm("Create","Restaurant",FormMethod.Post,new { id = "createForm" }))
{
    @Html.AntiForgeryToken()
    if (ViewData.ModelState[""] != null && ViewData.ModelState[""].Errors.Count > 0)
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            @Html.ValidationSummary(false)
        </div>
    }
    <div class="well">
        <fieldset class="col-md-12">
            <legend>Dados</legend>
            <label class="control-label col-md-1">Nome :</label>
            <div class="col-md-5">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "col-md-12" } })
            </div>
            <br />
            <br />
            <div class="row">
                <a href="@Url.Action("Index","Restaurant")" class="btn btn-sm btn-danger col-md-2" style="margin-right:2vw;"><i class="fa fa-undo"></i>&nbsp;Cancelar</a>
                <button type="submit" id="save" class="btn btn-sm btn-success col-md-2"><i class="fa fa-floppy-o"></i>&nbsp;Salvar</button>
            </div>
        </fieldset>
    </div>
}

@section scripts{
    <script>
        $('#createForm').on('submit', function (e) {
            if ($('#Name').val() == '') {
                alert("Nome é um campo obrigatório");
                e.preventDefault();
            }
        })
    </script>
}

AvaliacaoSawluz.Web/Views/Restaurant/Edit.cshtml
@model AvaliacaoSawluz.Data.Models.Restaurant

@{
    ViewBag.Title = "Cadastro de Restaurante";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>CADASTRO DE RESTAURANTE</h3>


@using (Html.BeginForm("Edit", "Restaurant", FormMethod.Post, new { id = "createForm" }))
{
    @Html.HiddenFor(model => model.Id)
    @Html.AntiForgeryToken()
    if (ViewData.ModelState[""] != null && ViewData.ModelState[""].Errors.Count > 0)
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">×</button>
            @Html.ValidationSummary(false)
        </div>
    }
    <div class="well">
        <fieldset class="col-md-12">
            <legend>Dados</legend>
            <label class="control-label col-md-1">Nome :</label>
            <div class="col-md-5">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "col-md-12" } })
            </div>
            <br />
            <br />
            <div class="row">
                <a href="@Url.Action("Index","Restaurant")" class="btn btn-sm btn-danger col-md-2" style="margin-right:2vw;"><i class="fa fa-undo"></i>&nbsp;Cancelar</a>
                <button type="submit" id="save" class="btn btn-sm btn-success col-md-2"><i class="fa fa-floppy-o"></i>&nbsp;Salvar</button>
            </div>
        </fieldset>
    </div>
}

@section scripts{
    <script>
        $('#createForm').on('submit', function (e) {
            if ($('#Name').val() == '') {
                alert("Nome é um campo obrigatório");
                e.preventDefault();
            }
        })
    </script>
}

AvaliacaoSawluz.Web/Views/Restaurant/Index.cshtml
@model IEnumerable<AvaliacaoSawluz.Data.Models.Restaurant>

@{
    ViewBag.Title = "Restaurantes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>RESTAURANTES</h3>
@using (Html.BeginForm("Search", "Restaurant", FormMethod.Post, new { @class = "form-inline" }))
{
    <div class="well">
        <fieldset class="col-md-12">
            <legend>Filtros</legend>
            <label class="control-label col-md-1">Nome :</label>
            @Html.TextBox("Name", (string)ViewBag.Name, new {@class="col-md-5" })
            <br />
            <br />
            <div class="row">
                <button type="submit" class="btn btn-sm btn-primary col-md-2"><i class="fa fa-search"></i>&nbsp;Pesquisar</button>
                <a href="@Url.Action("Create","Restaurant")" class="btn btn-sm btn-success col-md-2" style="margin-left:2vw;"><i class="fa fa-plus"></i>&nbsp;Cadastrar novo Restaurante</a>
            </div>
        </fieldset>

    </div>
}
<table id="restaurants" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th class="col-md-1">&nbsp;</th>
            <th class="col-md-1">&nbsp;</th>
            <th class="col-md-10">
                @Html.DisplayNameFor(model => model.Name)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">
                    <i class="fa fa-minus remove-item" title="Excluir" data-url="@Url.Action("Delete","Restaurant",new { id= item.Id })" style="color:red;"></i>
                </td>
                <td class="text-center">
                    <i class="fa fa-pencil edit-item" title="Editar" data-url="@Url.Action("Edit","Restaurant",new { id= item.Id })" style="color:cornflowerblue;"></i>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>

            </tr>
        }
    </tbody>

</table>
@section scripts{
    <script>
        $(document).ready(function () {
            $('#restaurants').DataTable({
                paging: false,
                autoWidth: true,
                info: false,
                lengthChange: false,
                ordering: false,
                searching: false,
                pageLength: 15
            });

            $('.edit-item').on('click', function () {
                var url = $(this).data('url');
                location.href = url;
            });
            $('.remove-item').on('click', function () {
                var url = $(this).data('url');
                $.getJSON(url, function (result) {
                    if (result == "Success") {
                        location.reload(true);
                    } else {
                        alert("Ocorreu um erro ao remover o item selecionado");
                    }
                });
            });
        })
    </script>
}

AvaliacaoSawluz.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema de Cadastro de Restaurantes</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Restaurantes", "Index", "Restaurant")</li>
                    <li>@Html.ActionLink("Pratos", "Index", "Menu")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>